#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
/run/verbose 2

/run/initialize

/gps/particle e+
/gps/ene/mono 5 MeV
/gps/pos/centre 0 0 -10 cm
/gps/direction 0 0 1

/analysis/setFileName vis

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGLSQt
/vis/viewer/set/autoRefresh false
/vis/viewer/set/picking true
/vis/verbose errors
/vis/drawVolume

/vis/viewer/set/targetPoint 0 0 0 cm
/vis/viewer/set/viewpointVector 1 0.5 1
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
/vis/viewer/zoom 1.5

/vis/geometry/set/visibility World              0 no

/vis/geometry/set/colour Crystal    0     1     1     1     0.1
/vis/geometry/set/colour Coupler    0     1     1     1     0.1
/vis/geometry/set/colour Window     0     1     1     1     0.1
/vis/geometry/set/colour SiPM       0     1     1     1     0.1

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 1 cm
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
