#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
/run/verbose 2

/run/initialize

/gps/particle e+
/gps/ene/mono 5 MeV
/gps/pos/centre 0. 10. 0. cm
/gps/direction 0 -1 0

/analysis/setFileName vis

/run/beamOn 1

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 -1
/vis/viewer/set/lightsVector -1 1 1
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
/vis/viewer/zoom 2.5

/vis/geometry/set/visibility World 0 false

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
